# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
  modId="advancements_tracker"
  version="${file.jarVersion}"
  displayName="Advancements Tracker"
  # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
  #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
  displayURL="https://www.curseforge.com/minecraft/mc-mods/advancements-tracker"
  logoFile="logo.png"
  credits=""
  authors="Markus Bordihn"
  description='''Advancements Tracker is a Minecraft Forge Client Mod that simplifies the process of tracking and achieving advancements through an intuitive overlay with sorting and filtering options.'''

[[dependencies.advancements_tracker]]
  modId="forge"
  mandatory=true
  versionRange="[45,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.advancements_tracker]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.19.4,1.20)"
  ordering="NONE"
  side="BOTH"
